# Check data

### Calendar

In [1]:
import pandas as pd

df_calendar = pd.read_csv('raw_csv_data/calendar.csv')
df_calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [2]:
df_calendar = df_calendar.rename(columns={
    'wm_yr_wk': 'week_id',
    'weekday': 'weekday_name',
    'wday': 'weekday_number',
    'month': 'month_number',
    'year': 'year_number',
    'd': 'day_id',
    'event_name_1': 'event_name_primary',
    'event_type_1': 'event_type_primary',
    'event_name_2': 'event_name_secondary',
    'event_type_2': 'event_type_secondary',
    'snap_CA': 'snap_california',
    'snap_TX': 'snap_texas',
    'snap_WI': 'snap_wisconsin'
})

df_calendar['date'] = pd.to_datetime(df_calendar['date'])

In [3]:
df_calendar.head()

,date,week_id,weekday_name,weekday_number,month_number,year_number,day_id,event_name_primary,event_type_primary,event_name_secondary,event_type_secondary,snap_california,snap_texas,snap_wisconsin
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

### Sell Prices

In [4]:
df_sell_prices = pd.read_csv('raw_csv_data/sell_prices.csv')
df_sell_prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [5]:
df_sell_prices.columns

Index(['store_id', 'item_id', 'wm_yr_wk', 'sell_price'], dtype='object')

In [6]:
df_sell_prices = df_sell_prices.rename(columns={
    "item_id": "product_id",
    "wm_yr_wk": "week_id",
    "sell_price": "price"
})

df_sell_prices.head()

  store_id     product_id  week_id  price
0     CA_1  HOBBIES_1_001    11325   9.58
1     CA_1  HOBBIES_1_001    11326   9.58
2     CA_1  HOBBIES_1_001    11327   8.26
3     CA_1  HOBBIES_1_001    11328   8.26
4     CA_1  HOBBIES_1_001    11329   8.26

### Sales Train

In [7]:
df_sales = pd.read_csv('raw_csv_data/sales_train_evaluation.csv')
df_sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

In [8]:
df_sales.columns

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4',
       ...
       'd_1932', 'd_1933', 'd_1934', 'd_1935', 'd_1936', 'd_1937', 'd_1938',
       'd_1939', 'd_1940', 'd_1941'],
      dtype='object', length=1947)

In [9]:
df_sales = df_sales.rename(columns={
    "id": "series_id",
    "item_id": "product_id",
    "dept_id": "department_id",
    "cat_id": "category_id",
    "state_id": "state_code"
})

In [10]:
df_sales.head()

,series_id,product_id,department_id,category_id,store_id,state_code,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

### Monster

In [11]:
import pandas as pd
from pathlib import Path

Path("monster_parts").mkdir(exist_ok=True)

id_vars = [
    "series_id","product_id","department_id",
    "category_id","store_id","state_code"
]

chunks = []
for store, df_store in df_sales.groupby("store_id"):
    print(f"Processing store {store} …")
    df_long = df_store.melt(id_vars=id_vars, var_name="day_id", value_name="sales")
    df_long = df_long.merge(df_calendar, how="left", on="day_id")
    df_long = df_long.merge(df_sell_prices, how="left",
                            on=["store_id","product_id","week_id"])
    df_long = df_long.sort_values(["product_id", "day_id"])
    fn = Path("monster_parts") / f"monster_{store}.parquet"
    df_long.to_parquet(fn, compression="snappy", index=False)
    print("   ✔ saved", fn)

Processing store CA_1 …
   ✔ saved monster_parts/monster_CA_1.parquet
Processing store CA_2 …
   ✔ saved monster_parts/monster_CA_2.parquet
Processing store CA_3 …
   ✔ saved monster_parts/monster_CA_3.parquet
Processing store CA_4 …
   ✔ saved monster_parts/monster_CA_4.parquet
Processing store TX_1 …
   ✔ saved monster_parts/monster_TX_1.parquet
Processing store TX_2 …
   ✔ saved monster_parts/monster_TX_2.parquet
Processing store TX_3 …
   ✔ saved monster_parts/monster_TX_3.parquet
Processing store WI_1 …
   ✔ saved monster_parts/monster_WI_1.parquet
Processing store WI_2 …
   ✔ saved monster_parts/monster_WI_2.parquet
Processing store WI_3 …
   ✔ saved monster_parts/monster_WI_3.parquet

In [12]:
from pathlib import Path

folder = Path("monster_parts")

for f in sorted(folder.glob("monster_*.parquet")):
    size_mb = f.stat().st_size / 1024 ** 2
    print(f"{f.name:<35}  {size_mb:8.1f} MB")

monster_CA_1.parquet                     25.0 MB
monster_CA_2.parquet                     24.7 MB
monster_CA_3.parquet                     25.4 MB
monster_CA_4.parquet                     24.5 MB
monster_TX_1.parquet                     24.7 MB
monster_TX_2.parquet                     24.9 MB
monster_TX_3.parquet                     24.7 MB
monster_WI_1.parquet                     24.7 MB
monster_WI_2.parquet                     24.6 MB
monster_WI_3.parquet                     24.7 MB

In [13]:
import pandas as pd

for f in sorted(folder.glob("monster_*.parquet")):
    n = len(pd.read_parquet(f, columns=["sales"]))   # read just one column
    print(f"{f.name:<35}  {n:>10,} rows")

monster_CA_1.parquet                  5,918,109 rows
monster_CA_2.parquet                  5,918,109 rows
monster_CA_3.parquet                  5,918,109 rows
monster_CA_4.parquet                  5,918,109 rows
monster_TX_1.parquet                  5,918,109 rows
monster_TX_2.parquet                  5,918,109 rows
monster_TX_3.parquet                  5,918,109 rows
monster_WI_1.parquet                  5,918,109 rows
monster_WI_2.parquet                  5,918,109 rows
monster_WI_3.parquet                  5,918,109 rows

In [14]:
files = sorted(folder.glob("monster_*.parquet"))
total_rows = sum(
    len(pd.read_parquet(f, columns=["sales"])) for f in files
)
print(f"Total rows across {len(files)} parts: {total_rows:,}")

Total rows across 10 parts: 59,181,090